name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run App Test (placeholder)
      run: echo "No tests configured"

    - name: Build Docker Image
      run: docker build -t my-webapp .

    - name: Push to DockerHub
      run: |
             echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
             docker tag my-webapp mayuresh23/my-webapp
             docker push mayuresh23/my-webapp
